Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	2	create_control_files
	4	run_indelible
	7
Select jobs to execute...

[Mon Jan 25 11:59:04 2021]
rule create_control_files:
    output: indelible/40_control.txt
    jobid: 2
    wildcards: taxon=40

[Mon Jan 25 11:59:04 2021]
Finished job 2.
1 of 7 steps (14%) done
Select jobs to execute...

[Mon Jan 25 11:59:04 2021]
rule run_indelible:
    input: indelible/40_control.txt
    output: indelible_output/40/cleaned_trees/40_tree_1.nwk, indelible_output/40/cleaned_fasta/40_TRUE_1.fasta
    jobid: 1
    wildcards: taxon=40, rep=1

[Mon Jan 25 11:59:05 2021]
Error in rule run_indelible:
    jobid: 1
    output: indelible_output/40/cleaned_trees/40_tree_1.nwk, indelible_output/40/cleaned_fasta/40_TRUE_1.fasta

RuleException:
CalledProcessError in line 24 of /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile:
Command 'set -euo pipefail;  /Users/gabefoley/miniconda3_latest/envs/indel_snakemake/bin/python3.9 /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/scripts/tmpaga8q012.run_indelible.py' returned non-zero exit status 1.
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile", line 24, in __rule_run_indelible
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/log/2021-01-25T115904.460486.snakemake.log
