Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	2	clean_fastml_ml
	2	clean_fastml_parsimony
	1	compile_latex
	6	concat_fasta
	2	concat_fastml__ml_summaries
	2	concat_fastml_summaries
	2	concat_indelible_summaries
	8	concat_summaries
	1	generate_latex
	1	generate_output_dict
	1	get_indelible_dict
	1	run_fastml
	4	run_grasp
	2	summarise_fastml_ml_indels
	2	summarise_fastml_parsimony_indels
	2	summarise_indelible
	8	summarise_indels
	47
Select jobs to execute...

[Fri Feb  5 09:16:01 2021]
rule clean_fastml_parsimony:
    input: fastml_results/5/1/seq.marginal_Chars_ParsimonyIndels.txt, fastml_results/5/1/tree.newick.txt
    output: fastml_results_parsimony/5/concatenated/1/FastML_ancestors.fasta, fastml_results_parsimony/5/cleaned_trees/1/tree.nwk, fastml_results_parsimony/5/cleaned_N0_trees/1/tree.nwk
    jobid: 47
    wildcards: taxon=5, rep=1

[Fri Feb  5 09:16:02 2021]
Error in rule clean_fastml_parsimony:
    jobid: 47
    output: fastml_results_parsimony/5/concatenated/1/FastML_ancestors.fasta, fastml_results_parsimony/5/cleaned_trees/1/tree.nwk, fastml_results_parsimony/5/cleaned_N0_trees/1/tree.nwk

RuleException:
CalledProcessError in line 74 of /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile:
Command 'set -euo pipefail;  /Users/gabefoley/miniconda3_latest/envs/indel_snakemake/bin/python3.9 /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/scripts/tmpf43667q6.clean_fastml.py' returned non-zero exit status 1.
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile", line 74, in __rule_clean_fastml_parsimony
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/log/2021-02-05T091601.419539.snakemake.log
