Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	4	concat_fasta
	3	concat_summaries
	1	create_plots
	2	run_grasp
	6	summarise_indels
	16
Select jobs to execute...

[Mon Feb  1 09:34:43 2021]
rule summarise_indels:
    input: grasp_results/6/SICML/1/tree.nwk, grasp_results/concatenated/6/SICML/1/GRASP_ancestors.fasta, indelible_output/6/cleaned_N0_trees/1.nwk, indelible_output/6/concatenated/1.fasta, indelible_dicts/6/leaves_1.p, indelible_dicts/6/gaps_1.p
    output: summaries/6/SICML/1.csv
    jobid: 25
    wildcards: taxon=6, method=SICML, rep=1

[Mon Feb  1 09:34:44 2021]
Error in rule summarise_indels:
    jobid: 25
    output: summaries/6/SICML/1.csv

RuleException:
CalledProcessError in line 123 of /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile:
Command 'set -euo pipefail;  /Users/gabefoley/miniconda3_latest/envs/indel_snakemake/bin/python3.9 /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/scripts/tmpr6sp0n_d.summarise_indels.py' returned non-zero exit status 1.
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile", line 123, in __rule_summarise_indels
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/log/2021-02-01T093443.651023.snakemake.log
