Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	4	clean_fasta
	2	create_control_files
	4	run_indelible
	4	split_trees
	15
Select jobs to execute...

[Sun Jan 24 23:33:20 2021]
rule create_control_files:
    output: indelible/40_control.txt
    jobid: 3
    wildcards: taxon=40

[Sun Jan 24 23:33:20 2021]
Finished job 3.
1 of 15 steps (7%) done
Select jobs to execute...

[Sun Jan 24 23:33:20 2021]
rule create_control_files:
    output: indelible/80_control.txt
    jobid: 8
    wildcards: taxon=80

[Sun Jan 24 23:33:20 2021]
Finished job 8.
2 of 15 steps (13%) done
Select jobs to execute...

[Sun Jan 24 23:33:20 2021]
rule run_indelible:
    input: indelible/80_control.txt
    output: indelible_output/80/80_TRUE_2.fasta
    jobid: 10
    wildcards: taxon=80, rep=2

[Sun Jan 24 23:33:21 2021]
Finished job 10.
3 of 15 steps (20%) done
Select jobs to execute...

[Sun Jan 24 23:33:21 2021]
rule run_indelible:
    input: indelible/40_control.txt
    output: indelible_output/40/40_TRUE_1.fasta
    jobid: 2
    wildcards: taxon=40, rep=1

[Sun Jan 24 23:33:21 2021]
Finished job 2.
4 of 15 steps (27%) done
Select jobs to execute...

[Sun Jan 24 23:33:21 2021]
rule clean_fasta:
    input: indelible_output/40/40_TRUE_1.fasta
    output: indelible_output/cleaned_aln/40/40_TRUE_1.fasta
    jobid: 11
    wildcards: taxon=40, rep=1

[Sun Jan 24 23:33:21 2021]
Error in rule clean_fasta:
    jobid: 11
    output: indelible_output/cleaned_aln/40/40_TRUE_1.fasta

RuleException:
CalledProcessError in line 41 of /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile:
Command 'set -euo pipefail;  /Users/gabefoley/miniconda3_latest/envs/indel_snakemake/bin/python3.9 /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/scripts/tmp0cgqcg1o.tidy_output.py' returned non-zero exit status 1.
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2319, in run_wrapper
  File "/Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/Snakefile", line 41, in __rule_clean_fasta
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/Users/gabefoley/miniconda3_latest/envs/indel_snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2350, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/gabefoley/Dropbox/PhD/20210121_Indel_Evaluation_Project/Indel_Evaluation_Snakemake/.snakemake/log/2021-01-24T233319.983819.snakemake.log
